addon_service/addon_imp/instantiation.py
addon_service/authorized_citation_account/models.py
addon_service/authorized_citation_account/serializers.py
addon_service/authorized_citation_account/views.py
addon_service/configured_citation_addon/models.py
addon_service/configured_citation_addon/serializers.py
addon_service/configured_citation_addon/views.py
addon_service/external_citation_service/__init__.py
addon_service/external_citation_service/models.py
addon_service/external_citation_service/serializers.py
addon_service/external_citation_service/views.py
addon_service/migrations/0001_initial.py
addon_service/models.py
addon_toolkit/interfaces/citation.py

`AuthorizedCitationAccount` Implementation (Task: **ENG-5976**)

- AuthorizedCitationAccount Implementation

---

addon_service/configured_citation_addon/models.py
addon_service/configured_citation_addon/serializers.py
addon_service/configured_citation_addon/views.py
addon_service/serializers.py
addon_toolkit/interfaces/citation.py

Implemented ConfiguredCitationAddon.

[ENG-5978] ConfiguredCitationAddon

---

addon_toolkit/interfaces/citation.py

Interface for Citations, supporting all necessary operations

[ENG-5990] Citation interface proposal

---

addon_imps/storage/box_dot_com.py
addon_imps/storage/figshare.py
addon_imps/storage/google_drive.py
addon_service/addon_imp/instantiation.py
addon_service/common/exceptions.py
addon_service/common/known_imps.py
addon_service/common/network.py
addon_toolkit/async_utils.py
addon_toolkit/constrained_network/http.py
addon_toolkit/imp.py
addon_toolkit/interfaces/citation.py
addon_toolkit/interfaces/storage.py
addon_toolkit/iri_utils.py
addon_toolkit/json_arguments.py

[ENG-6038] Implement FigshareStorageAddonImp

---

addon_imps/tests/storage/test_zotero.py

- Added tests for Zotero Api;
Tiket: https://openscience.atlassian.net/browse/ENG-6220

[ENG-6220]- Write Tests for Zotero API in GV

---

addon_service/configured_addon/citation/serializers.py
addon_service/configured_addon/models.py
addon_service/configured_addon/storage/serializers.py

Fixed ENG-6386
This PR should also have fixed ENG-6317, but for some reason haven't

[ENG-6386] added external_*_service links for configured addons

---

addon_imps/storage/box_dot_com.py
addon_imps/storage/dataverse.py
addon_imps/storage/figshare.py
addon_imps/storage/github.py
addon_service/tests/test_by_type/test_addon_operation_invocation.py
addon_toolkit/interfaces/storage.py
addon_toolkit/json_arguments.py

added `can_be_root` and `may_contain_root_candidates` properties for storage addons ItemResult

[ENG-6437] GV: Add new flags to ItemResult class

---

addon_imps/storage/owncloud.py
addon_service/common/credentials_formats.py
addon_service/common/known_imps.py
addon_service/common/network.py
addon_service/external_service/storage/models.py
addon_toolkit/constrained_network/http.py

Implemented **`Owncloud Storage Addon`**. For more details look at ticket **`ENG-6043`**

[ENG-6043] OwncloudAPI Storage Implementation

---

app/env.py
app/settings.py
poetry.lock
pyproject.toml

Integrate NewRelic with Gravy.
- Add `newrelic` dependency, update `poetry.lock`
- Initialize NewRelic agent where Sentry is also being initialized
- There may be a better place for application-init calls to go.
- This will require Helm chart and config changes to take effect, but should be relatively low-risk.

[ENG-5975] NewRelic Instrumentation

---

addon_imps/tests/storage/test_bitbucket.py

**Bitbucket** Unit Tests implementation | **`[ENG-6254]`**
[ENG-6254]: https://openscience.atlassian.net/browse/ENG-6254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-6254] |  Bitbucket Unit Tests implementation

---

addon_imps/storage/dropbox.py

Fixed Dropbox to provide path of root folder instead of root folder id

[ENG-6557] [ENG-6565][ENG-6556][ENG-6555] [ENG-6553] fixed wb settings for dropbox

---

addon_imps/storage/bitbucket.py
addon_imps/storage/owncloud.py
addon_imps/tests/storage/test_bitbucket.py
addon_service/common/waterbutler_compat.py

[ENG-6569] |  wb_config fix for Owncloud and Bitbucket + Owncloud Implementation Connection Fix bug
[ENG-6569]: https://openscience.atlassian.net/browse/ENG-6569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-6569] |  wb_config fix for Owncloud and Bitbucket + Owncloud Implementation Connection Fix bug

---

addon_imps/storage/owncloud.py
addon_service/authorized_account/models.py
addon_service/authorized_account/serializers.py

1. Fixed xml parse error message to be more user friendly
2. Fixed service not available scenario for all addons

[ENG-6695] fixed owncloud errors related to host url

---

addon_imps/storage/gitlab.py
addon_imps/tests/storage/test_gitlab.py

[ENG-6612] [ENG-6597] Fix/gitlab token validation

---

addon_imps/storage/dropbox.py
addon_imps/tests/storage/test_dropbox.py

Fixed cursor being returned when there aren't any items on new pages

[ENG-6582] Dropbox Configuration: "Load More" button not working 

---

addon_service/common/permissions.py

Added message to permission denied response, valid message is not appearing though

[ENG-6527]added message to permission class

---

addon_imps/storage/bitbucket.py
addon_imps/tests/storage/test_bitbucket.py

`[ENG-6672]` |  fixed bug when workspace item_type selected for Bitbucket
[ENG-6672]: https://openscience.atlassian.net/browse/ENG-6672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-6672] |  fixed bug when workspace item_type selected for Bitbucket

---

addon_imps/storage/figshare.py
addon_imps/tests/storage/test_figshare.py

Fixed load more button appearing when not needed in all cases **EXCEPT** when user has item count multiple of page size (20)

[ENG-6748] Fix load more for figshare

---

addon_service/configured_addon/citation/serializers.py
addon_service/configured_addon/computing/serializers.py
addon_service/configured_addon/serializers.py
addon_service/configured_addon/storage/serializers.py

added current_user_is_owner field to configured addon serializers

[ENG-6744] FE: Contributors can "configure" others' addons

---

addon_imps/storage/owncloud.py

**`[ENG-6569]`** | fixed **owncloud** subfolder issues
[ENG-6569]: https://openscience.atlassian.net/browse/ENG-6569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-6569] | fixed owncloud subfolder issues

---

addon_service/authorized_account/serializers.py

Fixed oauth 1a flow not starting on account reconnetcion request

[ENG-6788] Zotero: "Error reconnecting account" message is displayed after attempt to reconnect account

---

addon_imps/citations/zotero_org.py

Added handling of  Zotero edgecase on `get_item_info` for library

[ENG-6792] Zotero: Reconfiguration error

---

addon_service/addon_imp/instantiation.py
addon_service/authorized_account/computing/models.py
addon_service/external_service/computing/models.py
addon_service/external_service/computing/serializers.py

* Update `supported features` list for computing addons
* Make sure those supported features are properly serialized so the terms-and-conditions page can be rendered
* Fix up Computing addon instantiation code to correctly instantiate.

[ENG-6774] export terms and conditions for boa/computing addons

---

addon_imps/computing/boa.py
addon_service/common/waterbutler_compat.py
addon_toolkit/interfaces/computing.py

Boa wants credentials, give it to them via the wb_config mechanism.

[ENG-6825] teach boa to use wb config

---

addon_service/management/commands/migrate_authorized_account.py
docker-compose.yml

- fixed dropbox errors
- minor optimisations
- added options to migrations to be able to run them selectively

[ENG-6932] 

---

addon_service/management/commands/migrate_authorized_account.py

added crutch to make oauth2 accounts migration work with quirk on access_token_only

[ENG-6932] Fix account migrations

---

addon_service/authorized_account/serializers.py

**`[ENG-7038 | ENG-7033]`**  added validation when trying to reconnect addons

[ENG-7038 | ENG-7033]  added validation for reconnection addons

---

addon_imps/storage/dataverse.py

fixed load more button appearing when not needed during dataverse setup

[ENG-7037] Dataverse: "Load more" button

---

addon_service/authorized_account/models.py
addon_service/common/network.py
addon_service/management/commands/refresh_addon_tokens.py

Reverts CenterForOpenScience/gravyvalet#223

Revert "Only refresh token if the token have expired when returning wb creds"

---

addon_imps/storage/dropbox.py

**`[ENG-7319]`** | Added `try except` to print out full error message if the issue persists
[ENG-7319]: https://openscience.atlassian.net/browse/ENG-7319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-7319] | Added `try except` to print out full error message if the issue persists

---

addon_service/authentication.py
addon_service/common/permissions.py

Follow-up bug fix for https://openscience.atlassian.net/browse/ENG-7755

[ENG-7755] Bug-fix: Fixed access token auth for user-references

---

addon_service/addon_operation_invocation/serializers.py
addon_service/authorized_account/serializers.py
addon_service/common/get_user_uri.py
addon_service/common/osf.py
addon_service/common/permissions.py
addon_service/configured_addon/serializers.py

Final fix for PAT:
- Found all instances of accessing user_reference_uri from session, replaced them with helper function call
- extracted getting user uri into helper function

[ENG-7755] Bug-fix: Final fix for PAT

---

addon_toolkit/interfaces/link.py

Follow-up fix for https://github.com/CenterForOpenScience/gravyvalet/pull/269
https://openscience.atlassian.net/browse/ENG-7785

[ENG-7785] Integration Bug-fix: Fix naming for `OutputManagementPlan`

---

addon_service/management/commands/fill_external_services.py
addon_service/management/commands/providers/providers.csv

added dataverse to fill_external_services script

[ENG-8023] 2.5.4 GV: Update local setup script to include link Dataverse link add-on

---

addon_service/configured_addon/models.py

https://openscience.atlassian.net/browse/ENG-8239

[ENG-8239] Fix parameters for log_gv_addon celery task

---

.github/workflows/run_gravyvalet_tests.yml

https://openscience.atlassian.net/browse/ENG-8143
Add generation of OpenApi schema to CI/CD
Add generation of OpenApi schema to CI/CD
N/A
N/A
N/A
N/A

[ENG-8143] Add generation of OpenApi schema to CI/CD

---

Dockerfile

modified dev build to include everything necessary

[ENG-8027] [ENG-6835] [ENG-8027] 4.1.4 GV/CE: Make two docker images, one for prod and one for develop

---

addon_imps/storage/gitlab.py

https://openscience.atlassian.net/browse/ENG-8551
Supports WB Upgrade Project (https://github.com/CenterForOpenScience/waterbutler/pull/463)

[ENG-8551] WB Upgrade - GV Support

---

addon_imps/storage/s3.py
addon_service/external_service/models.py
addon_service/external_service/storage/views.py

[//]: # (Link to a JIRA ticket if available.)
[//]: # (Briefly describe the purpose of this PR.)
[//]: # (Briefly describe or list your changes.)
[//]: # (Any possible side effects?)
[//]: # (Any API documentation updates?)
[//]: # (Any QA testing notes for QE?)
[//]: # (Any server configuration and deployment notes for CE?)

[ENG-8364] Successful reconnect with invalid S3 Secret Key
